### ISSUE TITLE
I want to study it

### ISSUE THREAD

**Issue by ToulthG** [novatorem/spotify-readme#1]

**Comment by novatorem** [comment]
What about it do you want to study? It looks like you're simply using my profile's spotify.

Did you follow the [setup instructions](https://github.com/novatorem/novatorem/blob/master/SetUp.md) I posted?

**Comment by ToulthG** [comment]
> 您想学习什么？看来您只是在使用我的个人资料的spotify。
> 
> 您是否遵循我发布的[设置说明](https://github.com/novatorem/novatorem/blob/master/SetUp.md)？

Actually I am a beginner, if you want I can’t use the spotify of your profile right now, I can delete it immediately

**Comment by ToulthG** [comment]
> What about it do you want to study? It looks like you're simply using my profile's spotify.
> 
> Did you follow the [setup instructions](https://github.com/novatorem/novatorem/blob/master/SetUp.md) I posted?

I feel so sorry

**Comment by ToulthG** [comment]
> What about it do you want to study? It looks like you're simply using my profile's spotify.
> 
> Did you follow the [setup instructions](https://github.com/novatorem/novatorem/blob/master/SetUp.md) I posted?

Where is Refresh Token?

**Comment by novatorem** [comment]
Hey, no worries. You can leave it as is while trying to set things up.

You need to use the refresh token in your vercel app to reauthenticate your spotify.
At what stage of the setup info are you stuck?

**Comment by ToulthG** [comment]
> 嘿，不用担心。您可以在尝试设置时保持原样。
> 
> 您需要在Vercel应用程序中使用刷新令牌来重新认证Spotify。
> 您停留在设置信息的哪个阶段？

I only did the first step

> Hey, no worries. You can leave it as is while trying to set things up.
> 
> You need to use the refresh token in your vercel app to reauthenticate your spotify.
> At what stage of the setup info are you stuck?

I only did the first step
<removed screenshot>

**Comment by ToulthG** [comment]
> Hey, no worries. You can leave it as is while trying to set things up.
> 
> You need to use the refresh token in your vercel app to reauthenticate your spotify.
> At what stage of the setup info are you stuck?

"You need to use the refresh token in your vercel app to reauthenticate your spotify."  I opened it, but I don't know how to do it...

<Screenshot removed by novatorem>

**Comment by novatorem** [comment]
I think for you it would be here:

https://vercel.com/toulgthg/toulgth-g/settings/environment-variables

Then I assume you got your Client ID, Secret, and Refresh token?
Don't paste them here, they should remain a secret to you and only you.

Also make sure you took the [api folder](https://github.com/novatorem/novatorem/tree/master/api) and placed it in your ReadMe.

**Comment by ToulthG** [comment]
> 我认为对您来说会在这里：
> 
> https://vercel.com/toulgthg/toulgth-g/settings/environment-variables
> 
> 然后，我假设您获得了“客户ID”，“机密”和“刷新”令牌？
> 不要将其粘贴在此处，它们应该对您（只有您）保持秘密。
> 
> 另外，请确保已将[api文件夹](https://github.com/novatorem/novatorem/tree/master/api)放置在自述文件中。

Just like this? I will open it after add https://accounts.spotify.com/authorize?client_id={SPOTIFY_CLIENT_ID}&response_type=code&scope=user-read-currently-playing,user-read-recently-played&redirect_uri=http://localhost/callback/
![Screenshot_20200803-231323_Chrome](https://user-images.githubusercontent.com/61505961/89197943-0b2ad080-d5df-11ea-9af9-8f5a53185673.jpg)

**Comment by novatorem** [comment]
So where there's `{...}`, you have to insert your variables. So {Spotify_Client_ID} is where you plug in your Client ID that you got from the dashboard. Also, you should delete your picture since it contains the variable.

Finally, Name is where Client ID, Client Secret, and Refresh Token go (but as defined in setup.md). Value is where the variables go.

**Comment by ToulthG** [comment]
> So where there's `{...}`, you have to insert your variables. So {Spotify_Client_ID} is where you plug in your Client ID that you got from the dashboard. Also, you should delete your picture since it contains the variable.
> 
> Finally, Name is where Client ID, Client Secret, and Refresh Token go (but as defined in setup.md). Value is where the variables go.

Ok, wait for me to study slowly... (forgive me for being stupid) Thank you very much for your patience to answer me, I think I should learn enough knowledge before coming back (I am from China, I don’t understand some words when I see English  ), I won’t waste your time anymore, thank you very much!

**Comment by ToulthG** [comment]
> So where there's `{...}`, you have to insert your variables. So {Spotify_Client_ID} is where you plug in your Client ID that you got from the dashboard. Also, you should delete your picture since it contains the variable.
> 
> Finally, Name is where Client ID, Client Secret, and Refresh Token go (but as defined in setup.md). Value is where the variables go.

谢谢您！

**Comment by novatorem** [comment]
No worries, might be hard when a lot of these don't translate well.

Good luck, leaving this open for now.

**Comment by ch374n** [comment]
Hi, @novatorem  
Looks like it breaks while playing podcast 
`[GET] /api/spotify-playing
20:18:03:30
[ERROR]	2020-10-17T14:48:03.537Z	b708d79d-60da-4a4d-a04c-c9df8b84bf0c	Exception on /api/spotify-playing [GET]
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/task/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/task/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./api/spotify-playing.py", line 112, in catch_all
    svg = makeSVG(data)
  File "./api/spotify-playing.py", line 93, in makeSVG
    img = loadImageB64(item["album"]["images"][1]["url"])
TypeError: 'NoneType' object is not subscriptable`
